// simple scientfic printing code
// replaces the uggly mess generated by msvcrt
// DeadFish Shitware, 2010-2013
#ifndef _SCIPRN_H_
#define _SCIPRN_H_
#include <stdlib.h>

#define ToString SciPrn
#ifdef _UNICODE
#define SciPrn SciPrnW
#else
#define SciPrn SciPrnA
#endif

int sciPrnA(char* text, double in);
int sciPrnW(wchar_t* text, double in);

class SciPrnA
{
	char text[26];
public:
	SciPrnA(int in) { itoa(in, text, 10); }
	SciPrnA(double in) { sciPrnA(text, in); }
	operator const char*() { return text; }
	operator char*() { return text; }
};

class SciPrnW
{
	wchar_t text[26];
public:
	SciPrnW(int in) { _itow(in, text, 10); }
	SciPrnW(double in) { sciPrnW(text, in); }
	operator const wchar_t*() { return text; }
	operator wchar_t*() { return text; }
};
	
#endif
