#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_ICON1                               100
#define BTN_ROMBUILD                            1000
#define EDT_EMUPATH                             1000
#define IDC_STATIC2                             1000
#define BTN_EMUPATH                             1001
#define BTN_OPTIONS                             1001
#define STC_ROMSIZE                             1001
#define BTN_ADDTRK                              1002
#define CHK_EMUSPAWN                            1002
#define BTN_REMTRK                              1003
#define CHK_EMUTERM                             1003
#define BTN_BUILDROM                            1004
#define IDC_COMBO1                              1004
#define BTN_RBOPTIONS                           1005
#define CHK_DACAVENC                            1005
#define CHK_CLASSICRB                           1006
#define IDC_STATIC3                             1006
#define EDT_LOOPEDSECT                          1007
#define STC_RBLINE1                             1007
#define EDT_TRACKPAUSE                          1008
#define STC_RBLINE2                             1008
#define EDT_ROMPAD                              1009
#define EDT_SCALE                               1011
#define BTN_ADDIMG                              1100
#define GRP_IMAGEFILE                           1101
#define IDC_YPOSEDT                             1102
#define IDC_EXPAND                              1103
#define IDC_VIEW                                1104
#define IDC_MINUI_80                            1105
#define IDC_MINUI_01                            1106
#define IDC_MINUI_02                            1107
#define IDC_MINUI_04                            1108
#define IDC_MINUI_08                            1109
#define IDC_MINUI_10                            1110
#define IDC_MINUI_20                            1111
#define GRP_TRKINFO                             1112
#define IDC_SELECTIMG                           1113
#define IDC_YPOS                                1114
#define IDC_YSIZE                               1115
#define IDC_YSIZEEDT                            1116
#define IDC_IMGBKG                              1117
#define BTN_DELIMG                              1118
#define IDC_LIST1                               1119
#define IDC_SPIN1                               1120
